### ISSUE TITLE
[BUG] Timed out while waiting for the WS endpoint URL to appear in stdout!

### ISSUE THREAD

**Issue by hanifydvsa** [Sparticuz/chromium#177]
## Environment

- `chromium` Version: 118.0.0
- `puppeteer-core` Version: 21.4.1
- Node.js Version: 16.x
- Lambda / GCF Runtime: nodejs16

## Expected Behavior

No errors and runs as expected running on AWS Lambda

## Current Behavior

We sometimes get this error

#TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!
    at ChromeLauncher.launch (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:149:23)
    at async parseHTMLToPDF (/var/task/index.js:66:21)
    at async Runtime.exports.handler (/var/task/index.js:128:21)

## Steps to Reproduce

Unable to reproduce all the time, it seems to be random, this is the code it errors at, specifically on const browser.

```
async function parseHTMLToPDF(html) {
    const browser = await puppeteer.launch({
        executablePath: await chromium.executablePath(),
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        headless: chromium.headless,
    });
    const page = await browser.newPage();
    await page.setContent(html);
    const pdf = await page.pdf(pdfParams);
    await browser.close();

    return pdf;
}
```

## Possible Solution

I am thinking whether it might be multiple run times at the same time. I initially had it at 30 seconds timeout for the whole lambda which ran fine on the old chromium method before upgrading to yours following a forced change from nodejs12 which meant we couldn't revert back to it and saw that this is the only repo working so I did the conversion following your npm help. I saw these timeout issues so tried increasing to 3 minutes but to no avail.

This does not seem to occur all the time and anyway of replicating the failure each and every time has not worked for me.

Your input would be greatly appreciated.

**Comment by hanifydvsa** [comment]
After updating the memory from 512MB to 1600MB as suggested in the readme.

I now get this:

`Message: Invoke Error 	{"errorType":"TimeoutError","errorMessage":"Timed out after waiting 30000ms","name":"TimeoutError","stack":["TimeoutError: Timed out after waiting 30000ms","    at /opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:510:19","    at /opt/nodejs/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:59978","    at t.f._next (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:11821)","    at t.next (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:6459)","    at t.<anonymous> (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:71381)","    at t._execute (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:28234)","    at t.execute (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:28057)","    at t.flush (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/third_party/rxjs/rxjs.js:3:32540)","    at listOnTimeout (node:internal/timers:559:17)","    at processTimers (node:internal/timers:502:7)"]}`

**Comment by Sparticuz** [comment]
Can you add `dumpio: true` to your puppeteer launch call?

**Comment by Sparticuz** [comment]
This might have been fixed by 119.0.2, please check and also add `dumpio: true`

**Comment by hanifydvsa** [comment]
Thanks @Sparticuz I cannot update the plugin yet as we are coming to a change freeze but I've done a dumpio:true just to see if it shows anything the next time it errors.

It seems to occur in clusters and then nothing for a few days, so I am just waiting and seeing what is going on. I shall certainly try your updated plugin asap though.

Many thanks for your support.

**Comment by hanifydvsa** [comment]
Hi @Sparticuz,

I got an error this morning but it wasn't an error that stopped it doing its job unlike before. Not sure if this extra parameter is a catch all or something and it will still continue but this is what was shown:

`Fontconfig error: No writable cache directories
DevTools listening on ws://127.0.0.1:45059/devtools/browser/22b6cc8a-e014-4540-b754-e125d8ac8ae6
[1220/084403.873041:ERROR:command_buffer_proxy_impl.cc(319)] GPU state invalid after WaitForGetOffsetInRange.
`

With the GPU state invalid the one flagging as the actual error which I get emailed every time one occurs.

**Comment by hanifydvsa** [comment]
Hi @Sparticuz 

I found a html that is created that always fails, the main issue is that it includes personal information so I can't include it here so not sure how I can proceed with that but I did update it to the latest version:

node_modules/@sparticuz/chromium": {
      "version": "119.0.2",

  "node_modules/puppeteer-core": {
      "version": "21.7.0",

But I still get the following and for this, it occurs every single time it is ran:

```
Message: Invoke Error 	
{
    "errorType": "TimeoutError",
    "errorMessage": "Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!",
    "name": "TimeoutError",
    "stack": [
        "TimeoutError: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout!",
        "    at ChromeLauncher.launch (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:139:23)",
        "    at async parseHTMLToPDF (/var/task/index.js:66:21)",
        "    at async Runtime.exports.handler (/var/task/index.js:128:21)"
    ]
}
```

**Comment by hanifydvsa** [comment]
Just to add to above @Sparticuz it seems to be 100% related to pages, I reduced it from 99 to 50 and it worked fine

**Comment by hanifydvsa** [comment]
Sorry @Sparticuz found the issue and all it was, was lack of memory for the lambda.

**Comment by Sparticuz** [comment]
Sorry missed the last comment, those are chromium errors, take a look at your launch arguments.

**Comment by hanifydvsa** [comment]
thanks @Sparticuz 

```
    const browser = await puppeteer.launch({
        executablePath: await chromium.executablePath(),
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        headless: chromium.headless,
        dumpio: true
    });
```

I cant see what else i can change though

**Comment by hanifydvsa** [comment]
@Sparticuz sorry to ping, any suggestions you can offer would be greatly appreciated as I cannot recreate this issue consistently

**Comment by hanifydvsa** [comment]
> Just to add more information, after adding dumpio: true I've seen I had to increase the /tmp ephemeral storage of my lambda.

Thanks though I thought I had it already quite high but i've changed to this, i would have thought this would be enough?

Description
Lambda function to convert html to pdf.
Memory
2560MB
Ephemeral storage
5000MB

**Comment by deathemperor** [comment]
`[0802/102300.449785:ERROR:command_buffer_proxy_impl.cc(132)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.` happens intermittently for me too

launch arguments:

```
[
  '--allow-pre-commit-input',
  '--disable-background-networking',
  '--disable-background-timer-throttling',
  '--disable-backgrounding-occluded-windows',
  '--disable-breakpad',
  '--disable-client-side-phishing-detection',
  '--disable-component-extensions-with-background-pages',
  '--disable-component-update',
  '--disable-default-apps',
  '--disable-dev-shm-usage',
  '--disable-extensions',
  '--disable-hang-monitor',
  '--disable-ipc-flooding-protection',
  '--disable-popup-blocking',
  '--disable-prompt-on-repost',
  '--disable-renderer-backgrounding',
  '--disable-sync',
  '--enable-automation',
  '--enable-blink-features=IdleDetection',
  '--export-tagged-pdf',
  '--force-color-profile=srgb',
  '--metrics-recording-only',
  '--no-first-run',
  '--password-store=basic',
  '--use-mock-keychain',
  '--disable-domain-reliability',
  '--disable-print-preview',
  '--disable-speech-api',
  '--disk-cache-size=33554432',
  '--mute-audio',
  '--no-default-browser-check',
  '--no-pings',
  '--single-process',
  '--font-render-hinting=none',
  '--disable-features=Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints,AudioServiceOutOfProcess,IsolateOrigins,site-per-process',
  '--enable-features=NetworkServiceInProcess2,SharedArrayBuffer',
  '--hide-scrollbars',
  '--ignore-gpu-blocklist',
  '--in-process-gpu',
  '--window-size=1920,1080',
  '--use-gl=angle',
  '--use-angle=swiftshader',
  '--allow-running-insecure-content',
  '--disable-setuid-sandbox',
  '--disable-site-isolation-trials',
  '--disable-web-security',
  '--no-sandbox',
  '--no-zygote',
  "--headless='shell'",
  '--disable-gpu',
  '--disable-lcd-text',
  '--font-render-hinting=none'
]
```

**Comment by Sparticuz** [comment]
Sorry for the delay, those seem like they are graphics stack errors, try disabling the graphics stack and reopen a new issue if you are still having issues.

**Comment by saran-karthik-my-digital** [comment]
ERROR Error processing request: Error: Unable to launch browser, error message: Timed out after 30000 ms while waiting for the WS endpoint URL to appear in stdout! at Cluster. 
So I did get this error and after reading out the bug, i just wanted to know, 
My ephemeral storage is 512MB and the Memory is 4096 MB. Should I increase the ephemeral storage or what should I do to avoid this?
