### ISSUE TITLE
browser.close() just hangs

### ISSUE THREAD

**Issue by calvinmetcalf** [Sparticuz/chromium#85]
## Environment
* `chromium` Version: 112.0.2
* `puppeteer` / `puppeteer-core` Version:  19.8.5
* Node.js Version:  16
* Lambda / GCF Runtime:  node 16

## Expected Behavior

`browser.close()` should resolve or reject

## Current Behavior
it just hangs, it doesn't when i pin to 19.7.2/111.0.0

## Steps to Reproduce
I'm doing very standard stuff that is mostly right out of the examples. the one thing I'm doing slightly out of the ordinary is that I am making a PDF of the page, all that stuff still works though it's *just* the call to close that isn't working.

## Possible Solution

not sure possibly related to #80 ?

**Comment by Sparticuz** [comment]
I've also not been able to get this working (ever), but since the lambda instance terminates chromium after the request anyways, I'm not sure it matters much to me.

puppeteer says that it's a void promise, so `await browser.close();` should be all you need.

**Comment by calvinmetcalf** [comment]
Yeah I guess as a work around I could just not await the browser.close
promise. I can try making a minimal reproducible case next week, it's just
towards the end of a very long set of step functions.

**Comment by mfaheemakhtar** [comment]
Updated the code today and started getting timeouts on server. I have been try to find the cause since morning. Good to find the reason and solution.

**Comment by NozzerFX** [comment]
I can confirm I have the same issue, environment the same except using Node 14.x.  I can confirm the suggested pinned versions fix the problem.

**Comment by huksley** [comment]
I also have the same issue, node16.x runtime, AWS Lambda have 4GB memory allocated

**Comment by Sparticuz** [comment]
Does this make any difference?
```
// Optional: If you'd like to use the legacy headless mode. "new" is the default.
chromium.setHeadlessMode = true;
```

**Comment by AVatch** [comment]
Setting `setHeadlessMode = true` does not make a difference on my end in regards to the `browser.close()` command hanging

**Comment by yspreen** [comment]
I'm on the latest version and running the browser like

```
    browser = await puppeteer.launch({
      args: isLambda ? chromium.args : undefined,
      defaultViewport: chromium.defaultViewport,
      executablePath: isLambda
        ? await chromium.executablePath()
        : "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    });
```

I found that I have to remove the args when running locally. and that closing the browser fails if the args are set. so it does appear that something in the args is preventing the browser to close properly.

**Comment by yspreen** [comment]
just to clarify: the browser won't launch at all locally if the args are set. but regardless where the browser is run, the close method hangs when the args are set

**Comment by yspreen** [comment]
using 112.0.2

**Comment by aaronce** [comment]
Hi all, Thought I'd add in my findings here as well.
- using 112.0.2
- using chromium.setHeadlessMode = true
- using page.pdf()

I don't think it's browser.close() that's the specific issue here, as I get lambda timeouts with and without it, as soon as `puppeteer.launch({})` is called in the lambda it continues until timeout.

side note, I also had this issue when using the "chrome-aws-lambda-17.1.1" older version.

So far what I've found that works is reducing right back the flags passed to puppeteer. Starting off with these ones below I now have no timeout issues and have maintained all functionality I required. Unfortunately I can't pin point the problem flag for you right now.

```
browser = await puppeteer.launch({
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--disable-gpu',
        '--single-process',
        '--disable-web-security',
        '--font-render-hinting=none',
      ],
      defaultViewport: chromium.defaultViewport,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
      ignoreHTTPSErrors: true,
    })
```

**Comment by vibou** [comment]
We have the same issue here. Don't know if it's help but here is the list of args from alixaxel/chrome-aws-lambda repository:

```javascript
const result = [
      '--allow-running-insecure-content', // https://source.chromium.org/search?q=lang:cpp+symbol:kAllowRunningInsecureContent&ss=chromium
      '--autoplay-policy=user-gesture-required', // https://source.chromium.org/search?q=lang:cpp+symbol:kAutoplayPolicy&ss=chromium
      '--disable-component-update', // https://source.chromium.org/search?q=lang:cpp+symbol:kDisableComponentUpdate&ss=chromium
      '--disable-domain-reliability', // https://source.chromium.org/search?q=lang:cpp+symbol:kDisableDomainReliability&ss=chromium
      '--disable-features=AudioServiceOutOfProcess,IsolateOrigins,site-per-process', // https://source.chromium.org/search?q=file:content_features.cc&ss=chromium
      '--disable-print-preview', // https://source.chromium.org/search?q=lang:cpp+symbol:kDisablePrintPreview&ss=chromium
      '--disable-setuid-sandbox', // https://source.chromium.org/search?q=lang:cpp+symbol:kDisableSetuidSandbox&ss=chromium
      '--disable-site-isolation-trials', // https://source.chromium.org/search?q=lang:cpp+symbol:kDisableSiteIsolation&ss=chromium
      '--disable-speech-api', // https://source.chromium.org/search?q=lang:cpp+symbol:kDisableSpeechAPI&ss=chromium
      '--disable-web-security', // https://source.chromium.org/search?q=lang:cpp+symbol:kDisableWebSecurity&ss=chromium
      '--disk-cache-size=33554432', // https://source.chromium.org/search?q=lang:cpp+symbol:kDiskCacheSize&ss=chromium
      '--enable-features=SharedArrayBuffer', // https://source.chromium.org/search?q=file:content_features.cc&ss=chromium
      '--hide-scrollbars', // https://source.chromium.org/search?q=lang:cpp+symbol:kHideScrollbars&ss=chromium
      '--ignore-gpu-blocklist', // https://source.chromium.org/search?q=lang:cpp+symbol:kIgnoreGpuBlocklist&ss=chromium
      '--in-process-gpu', // https://source.chromium.org/search?q=lang:cpp+symbol:kInProcessGPU&ss=chromium
      '--mute-audio', // https://source.chromium.org/search?q=lang:cpp+symbol:kMuteAudio&ss=chromium
      '--no-default-browser-check', // https://source.chromium.org/search?q=lang:cpp+symbol:kNoDefaultBrowserCheck&ss=chromium
      '--no-pings', // https://source.chromium.org/search?q=lang:cpp+symbol:kNoPings&ss=chromium
      '--no-sandbox', // https://source.chromium.org/search?q=lang:cpp+symbol:kNoSandbox&ss=chromium
      '--no-zygote', // https://source.chromium.org/search?q=lang:cpp+symbol:kNoZygote&ss=chromium
      '--use-gl=swiftshader', // https://source.chromium.org/search?q=lang:cpp+symbol:kUseGl&ss=chromium
      '--window-size=1920,1080', // https://source.chromium.org/search?q=lang:cpp+symbol:kWindowSize&ss=chromium
    ];
```

**Comment by acsbendi** [comment]
I can confirm that not only the call hangs, but the resources (e.g. temp files) used by the browser are also not cleaned up. As a workaround you can kill the browser process manually, which should also clean up the resources:
```typescript
browser = puppeteer.launch(...)
browserPid = browser.process()?.pid
...
if (browserPid) {
    process.kill(browserPid)
}
```

**Comment by aldenquimby** [comment]
I was hitting this problem with `v111.0.0` and adding `--disable-gpu` fixed it for me:
```ts
      playwright.launch({
        args: [...chromium.args, '--disable-gpu'],
        executablePath: await chromium.executablePath(),
      });
```

Thank you @aaronce for pointing me in this direction

**Comment by Sparticuz** [comment]
> I was hitting this problem with `v111.0.0` and adding `--disable-gpu` fixed it for me:

If you use `chromium.graphicsMode = false` before calling `chromium.executablePath()` instead of  spreading the `chromium.args` with `--disable-gpu`, you'll actually gain some extract speed because the webgl drivers won't be extracted.

```
chromium.graphicsMode = false;
playwright.launch({
        args: chromium.args,
        executablePath: await chromium.executablePath(),
      });
```

**Comment by aldenquimby** [comment]
@Sparticuz I will give that a try when we upgrade to v112, thank you!

**Comment by Tietew** [comment]
Same issue with AWS Lambda NodeJS *v18*.

Adding `chromium.setGraphicsMode = false;` helped me:

```js
  chromium.setGraphicsMode = false; // <= [*] added this line
  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: chromium.headless,
  });
  /* ... */
  await browser.close(); // <= hangs here WITHOUT [*]
```

**Comment by aldenquimby** [comment]
@Tietew watch out - even though `browser.close()` no longer hangs, it is very likely not actually releasing resources. You may eventually see this error in your Lambda CloudWatch logs:
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/2145098/235983005-e84f59e2-f02d-4975-8853-785ff1b78b6d.png">

To address this, we first doubled the size of `/tmp` by adding this to serverless.yml (notably jumping out of the free tier and starting to pay for space):
```
ephemeralStorageSize: 1024
```

But that just delayed the problem, we still hit out of space errors.

Our ultimate fix was to _not close the browser_. Use a singleton browser + page, and leave it to Lambda to clean up resources when the entire Lambda shuts down. This is currently working for us.

**Comment by aaronce** [comment]
@aldenquimby thanks for that information. I had considered a pattern like that myself, but was worried about leakage across invocations. I will monitor for that error now.

**Comment by Tietew** [comment]
I tested again on AWS Lambda NodeJS 18.x.
I could not reproduce any resource leak. There are no profile directory after closing chromium.

1. Launch chromium (with `chromium.setGraphicsMode = false;`)
2. Open a page, goto `https://en.wikipedia.org/`, print a PDF to buffer
3. Close chromium (`await browser.close()`)
4. Print process list, `ls -a /tmp`, and `df`
5. Return the PDF as a response of lambda

### First run
```
user agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/112.0.5614.0 Safari/537.36
ps:
1 /var/rapid/init --enable-extensions --bootstrap /var/runtime/bootstrap --logs-egress-api fluxpump --enable-msg-logs 
8 /var/lang/bin/node --expose-gc --max-http-header-size 81920 --max-semi-space-size=25 --max-old-space-size=461 /var/runtime/index.mjs
ls /tmp:
total 156432
drwx------  5 sbx_user1051  990      4096 May  9 06:27 .
drwxr-xr-x 17 root         root      4096 Nov  3  2022 ..
drwxrwxr-x  4 sbx_user1051  990      4096 May  9 06:08 aws
-rwx------  1 sbx_user1051  990 160176824 May  9 06:08 chromium
drwx------  2 sbx_user1051  990      4096 May  9 06:08 locales
df:
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/vde       105100160 102634232         0 100% /
/dev/vdb         1486216      9536   1460296   1% /dev
/dev/vdd          537560    160712    365012  31% /tmp
/dev/root       10153236    528640   9608212   6% /etc/passwd
/dev/vdc           59776     59776         0 100% /opt
```

### Second run
```
user agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/112.0.5614.0 Safari/537.36
ps:
1 /var/rapid/init --enable-extensions --bootstrap /var/runtime/bootstrap --logs-egress-api fluxpump --enable-msg-logs 
8 /var/lang/bin/node --expose-gc --max-http-header-size 81920 --max-semi-space-size=25 --max-old-space-size=461 /var/runtime/index.mjs 
ls /tmp:
total 156432
drwx------  5 sbx_user1051  990      4096 May  9 06:27 .
drwxr-xr-x 17 root         root      4096 Nov  3  2022 ..
drwxrwxr-x  4 sbx_user1051  990      4096 May  9 06:08 aws
-rwx------  1 sbx_user1051  990 160176824 May  9 06:08 chromium
drwx------  2 sbx_user1051  990      4096 May  9 06:08 locales
df:
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/vde       105100160 102634232         0 100% /
/dev/vdb         1486216      9532   1460300   1% /dev
/dev/vdd          537560    160712    365012  31% /tmp
/dev/root       10153236    528640   9608212   6% /etc/passwd
/dev/vdc           59776     59776         0 100% /opt
```

**Comment by doteric** [comment]
Had the same problem on AWS Lambda using node v18.

I noticed the following comment on a related bug report, but in the puppeteer GitHub: https://github.com/puppeteer/puppeteer/issues/7922#issuecomment-1549052725

So I went ahead and tried
```
const pages = await browser.pages();
for (const page of pages) {
  await page.close();
}
await browser.close();
```
and it seems to solve the problem of `browser.close` hanging. I guess this could potentially be a better option than killing the process, but I wonder if it actually closes the browser correctly.

**Comment by jeanbmar** [comment]
The issue happens with standalone Puppeteer package too.
From what I see in my local tests, enabling either `--use-gl=angle` **or** `--use-angle=swiftshader` will prevent browser from closing.

**Comment by Sparticuz** [comment]
> The issue happens with standalone Puppeteer package too. From what I see in my local tests, enabling either `--use-gl=angle` **or** `--use-angle=swiftshader` will prevent the browser from closing.

I suspected this was the case.

Since this is an upstream issue, I'll close this for now.

If you care about chromium closing properly, and don't need webgl, see this comment for a solution: https://github.com/Sparticuz/chromium/issues/85#issuecomment-1527692751

If you need webgl, I suppose you'll just need to be ok with just killing the instance.

**Comment by jandppw** [comment]
On Bitbucket Pipelines, using the official node Docker containers `node:16`, `node:18`, and `node:20`, and on macOS `13.5.2`, the issue exists. `await browser.close()` never resolves.

The `setGraphicsMode = false` solution does’nt do didly on either platform.

On macOS, the issue only occurs if the `browser.connected === false` when calling `browser.close()`.

This was resolved with

```
…
   const connected = browser.connected
   if (connected) {
      …
    } else {
      try {
        const killResult = browser.process().kill()
        console.log(`kill: ${killResult}`)
      } catch (err) {
        console.log('kill failed. giving up')
      }
    }
…
```

On Bitbucket Pipelines, using the official node Docker containers `node:16`, `node:18`, and `node:20`, the issue also exists when `browser.connected === true`.

I found out that there seems to be 1 page, even if no page has been created. Closing that (and any other pages that would hang around) resolved the issue on Bitbucket Pipelines, using the official node Docker containers `node:16`, `node:18`, and `node:20`.

```
…
   const connected = browser.connected
   if (connected) {
      const pages = await browser.pages()
      await Promise.all(pages.map(p => p.close()))
      await browser.close()
   }
…
```

**Comment by heaven** [comment]
Something is wrong, I started getting the same issue after the upgrade. Pages with the embedded player (youtube) freeze.

**Comment by josiahwiebe** [comment]
Just came here to say that adding 
```js
chromium.setGraphicsMode = false
```
to my code before `await puppeteer.launch()` fixed my issues with this. I was trying to get puppeteer to work with `@sparticuz/chromium-min` and deploy to Vercel, and this finally made it all work.

**Comment by mordechaim** [comment]
```
chromium.setGraphicsMode = false
```
did not help for me

```
browser.process().kill()
```
works perfectly for me, though a dirty solution TBH

**Comment by heaven** [comment]
@josiahwiebe for me that saved a second or a few during the startup but also did not solve the issue.

@mordechaim You may need to clean up the /tmp before each run because this approach will leave the cache there and will eventually lead to out-of-space errors.

Downgrade helped.

**Comment by jared-w-smith** [comment]
I was also experiencing browser.close() hanging about .5% of the time when using code that worked flawlessly on older versions of Puppeteer. The following solution has worked flawlessly - just replace `browser.close()` with:
`await Promise.race([browser.close(), browser.close(), browser.close()]);`

Apparently triggering the close method multiple times does the trick.

**Comment by hasan-wajahat** [comment]
I am facing an interesting issue, I am on the version 123 of the chromium package and have bunch of additions to the chromium args with things like `--disable-gpu`.  But as soon as I add ` chromium.setGraphicsMode = false; ` my lambdas start to timeout. Has anybody else faced an issue like this?

**Comment by adrians5j** [comment]
Was experiencing the hangout as well in AWS Lambda. Ultimately, looks like killing the browser process, instead of closing the browser resolved the issue. We have yet to see if there will be any side effects with doing this. 🤔

**Comment by ikerya** [comment]
Same. Simply opening a page, then relaunching browser, closing the old one, and browser.close just hangs after 5s of script execution. 24.6.1
